apiVersion: v1
kind: Service
metadata:
  name: memorix
  namespace: rag-etl
  labels:
    k8s-app: memorix
    qcloud-app: memorix
    service.cloud.tencent.com/loadbalance-type: INTERNAL
  annotations:
    # service.kubernetes.io/qcloud-loadbalancer-internal-subnetid: <subnet-id>
    # service.kubernetes.io/tke-existed-lbid: <lb-id>
    # service.kubernetes.io/qcloud-share-existed-lb: "true"
spec:
  type: LoadBalancer
  selector:
    k8s-app: memorix
    qcloud-app: memorix
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
  sessionAffinity: None
