apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: memorix-uploads-pvc
  namespace: memorix
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  # storageClassName: standard   # Set to your cluster's StorageClass name
