package domain

import (
	"encoding/json"
	"time"
)

// Experience represents a historical experience extracted from conversations.
// This is the core data model for the Experience Recall Layer - a dedicated
// vector storage layer for semantic retrieval of past experiences.
//
// Unlike memories (which are current knowledge), experiences are historical
// events that provide context for future decisions. Examples:
// - "Tried using Redis for caching, but hit memory limits with large datasets"
// - "Debug session revealed root cause was missing null check in user service"
// - "User prefers concise explanations with code examples"
type Experience struct {
	// Primary identifier
	ExperienceID string `json:"experience_id"`

	// User isolation - all experiences are scoped to a specific user
	UserID string `json:"user_id"`

	// Core content - the experience description
	Content string `json:"content"`

	// Vector embedding for semantic search (generated by embedding pipeline)
	Embedding []float32 `json:"-"` // Omitted from JSON, stored separately in vector DB

	// Metadata for filtering and context
	Metadata ExperienceMetadata `json:"metadata"`

	// Lifecycle timestamps
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`

	// Similarity score (only populated in search results)
	Score *float64 `json:"score,omitempty"`
}

// ExperienceMetadata contains structured metadata for an experience.
type ExperienceMetadata struct {
	// Session this experience originated from
	SessionID string `json:"session_id,omitempty"`

	// Topic category (e.g., "debugging", "architecture", "preferences")
	Topic string `json:"topic,omitempty"`

	// Outcome of this experience (success, failure, learning)
	Outcome ExperienceOutcome `json:"outcome,omitempty"`

	// Confidence score for extracted experiences (0.0-1.0)
	Confidence float64 `json:"confidence,omitempty"`

	// Tags for additional categorization
	Tags []string `json:"tags,omitempty"`

	// Source agent that created this experience
	Source string `json:"source,omitempty"`

	// Additional structured data
	Extra json.RawMessage `json:"extra,omitempty"`
}

// ExperienceOutcome represents the result of an experience.
type ExperienceOutcome string

const (
	OutcomeSuccess  ExperienceOutcome = "success"  // Successful outcome
	OutcomeFailure  ExperienceOutcome = "failure"  // Failed attempt, learned from it
	OutcomeLearning ExperienceOutcome = "learning" // General learning, no clear success/failure
	OutcomeNeutral  ExperienceOutcome = "neutral"  // Outcome not determined
)

// ExperienceFilter encapsulates query parameters for experience retrieval.
type ExperienceFilter struct {
	UserID    string            // Required: user isolation
	Query     string            // Semantic search query
	Topic     string            // Filter by topic
	Outcome   ExperienceOutcome // Filter by outcome
	Tags      []string          // Filter by tags (AND)
	SessionID string            // Filter by session
	MinScore  float64           // Minimum similarity score (0-1)
	Limit     int               // Max results (default 10, max 100)
	Offset    int               // Pagination offset
}

// ExperienceWriteRequest contains data for writing a new experience.
type ExperienceWriteRequest struct {
	UserID      string             `json:"user_id"`
	Content     string             `json:"content"`
	SessionID   string             `json:"session_id,omitempty"`
	Topic       string             `json:"topic,omitempty"`
	Outcome     ExperienceOutcome  `json:"outcome,omitempty"`
	Confidence  float64            `json:"confidence,omitempty"`
	Tags        []string           `json:"tags,omitempty"`
	Source      string             `json:"source,omitempty"`
	Extra       json.RawMessage    `json:"extra,omitempty"`
}

// ExperienceSearchResult contains the result of an experience search.
type ExperienceSearchResult struct {
	Experiences []Experience `json:"experiences"`
	Total       int          `json:"total"`
	Query       string       `json:"query"`
	LatencyMs   int64        `json:"latency_ms"` // Retrieval latency in milliseconds
}

// ExperienceStats contains statistics about stored experiences.
type ExperienceStats struct {
	UserID            string `json:"user_id"`
	TotalExperiences  int    `json:"total_experiences"`
	ByTopic           map[string]int `json:"by_topic"`
	ByOutcome         map[ExperienceOutcome]int `json:"by_outcome"`
	OldestExperience  *time.Time `json:"oldest_experience,omitempty"`
	NewestExperience  *time.Time `json:"newest_experience,omitempty"`
	AverageContentLen float64 `json:"average_content_len"`
}

// Valid outcomes
func ValidOutcomes() []ExperienceOutcome {
	return []ExperienceOutcome{
		OutcomeSuccess,
		OutcomeFailure,
		OutcomeLearning,
		OutcomeNeutral,
	}
}

func IsValidOutcome(o ExperienceOutcome) bool {
	for _, valid := range ValidOutcomes() {
		if o == valid {
			return true
		}
	}
	return false
}

// Default limits
const (
	DefaultExperienceLimit = 10
	MaxExperienceLimit     = 100
	MaxExperienceContent   = 10000 // Max content length in characters
	MaxExperienceTags      = 20
	MinExperienceConfidence = 0.0
	MaxExperienceConfidence = 1.0
)
